name: 'Build and Test'

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/get_latest_release
        id: version-info
        with:
          main-branch: master
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: ./.github/actions/gradle_cache
      - name: Generate Assets
        run: ./gradlew -Pversion=${{ steps.version-info.outputs.version }} runData
      - name: Build
        run: ./gradlew -Pversion=${{ steps.version-info.outputs.version }} build -x test -x check
      - name: Upload new Source Text Strings to Crowdin
        run: ./gradlew -Pversion=${{ steps.version-info.outputs.version }} uploadToCrowdin
        env:
          GIT_BRANCH: master
          CROWDIN_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
        continue-on-error: true
        if: github.ref == 'refs/heads/master'
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: build/libs/

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: ./.github/actions/gradle_cache
      - name: Generate Assets
        run: ./gradlew runData
      - name: Test
        run: ./gradlew check
